# For pre-commit.ci
ci:
  # Defer autoupdate to quarterly (there is no 'off' button) to have renovate pick up first
  autoupdate_schedule: quarterly
  submodules: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: no-commit-to-branch
        name: "Verifying git branch exists"
        args:
          - --branch=main
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: "Linting yaml"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: "Verifying/updating code with prettier"
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        name: "Linting Markdown"
