name: Plugwise differences

env:
  CACHE_VERSION: 3

on:
  schedule:
    - cron: '0 0 * * *' # weekly
  workflow_dispatch:
#  push:

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Prepare environment
    steps:
    - name: Check out our own code
      uses: actions/checkout@v2
    - name: Restore base environment
      id: restore-clones
      uses: actions/cache@v2
      with:
        path: clones
        key: >-
          ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-${{ hashFiles('scripts/setup.sh') }}-${{ hashFiles('scripts.diffy.sh') }}
    - name: Cache base diff environment
      id: cache-clones
      if: steps.restore-clones.outputs.cache-hit != 'true'
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          clones
          **/node_modules
        key: >-
          ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-${{ hashFiles('scripts/setup.sh') }}-${{ hashFiles('scripts.diffy.sh') }}
        restore-keys: |
          ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-${{ hashFiles('scripts/setup.sh') }}-${{ hashFiles('scripts.diffy.sh') }}
          ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-${{ hashFiles('scripts/setup.sh') }}
          ${{ env.CACHE_VERSION}}-${{ runner.os }}-base
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install diff2html
      run: npm -g install diff2html-cli diff2html
    - name: Checkout HA core
      uses: actions/checkout@v2
      with:
        repository: home-assistant/core
        path: clones/ha-core
    - name: Checkout Plugwise fork of HA core
      uses: actions/checkout@v2
      with:
        repository: plugwise/home-assistant.core
        ssh-key: ${{ secrets.hacore_deploykey }}
        path: clones/pw-core
        fetch-depth: 0
    - name: Checkout beta component (branch-switch)
      uses: actions/checkout@v2
      with:
        repository: plugwise/plugwise-beta
        ssh-key: ${{ secrets.hacore_deploykey }}
        path: clones/beta
        fetch-depth: 0
    - name: Checkout beta component (branch-switch)
      uses: actions/checkout@v2
      with:
        repository: plugwise/plugwise-beta
        ssh-key: ${{ secrets.plugwise_deploykey }}
        path: clones/beta-master

    - name: Setup clones
      run: scripts/setup.sh
    - name: Run diffy
      env:
        PROGRESS_DEPLOYKEY: {{ secrets.PROGRESS_DEPLOYKEY }}
      run: scripts/diffy.sh


