name: Plugwise differences

env:
  CACHE_VERSION: 2

on:
  schedule:
    - cron: '0 0 * * 0' # weekly
  push:

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Prepare environment
    steps:
    - name: Check out our own code
      uses: actions/checkout@v2
    - name: Cache base diff environment
      id: cache-clones
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          clones
          **/node_modules
        key: >-
          ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-${{ hashFiles('scripts/setup.sh') }}
        restore-keys: |
          ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-${{ hashFiles('scripts/setup.sh') }}
          ${{ env.CACHE_VERSION}}-${{ runner.os }}-base
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install diff2html
      run: npm install diff2html
    - name: Setup clones
      run: scripts/setup.sh

  diff:
    runs-on: ubuntu-latest
    name: Check for differences
    needs: prepare
    steps:
    - name: Check out our own code
      uses: actions/checkout@v2
    - name: Restore base environment
      id: cache-clones
      uses: actions/cache@v2
      with:
        path: clones
        key: >-
          ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-${{ hashFiles('scripts/setup.sh') }}
    - name: Fail job if cache restore failed
      if: steps.cache-clones.outputs.cache-hit != 'true'
      run: |
        echo "Failed to restore environment from cache"
        exit 1
    - name: Run diffy
      run: scripts/diffy.sh
