name: Plugwise differences

env:
  CACHE_VERSION: 6

on:
  schedule:
    - cron: '0 0 * * *' # weekly
  workflow_dispatch:
  push:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  prepare:
    runs-on: ubuntu-latest
    name: Prepare environment
    needs: shellcheck
    steps:
    - name: Check out our own code
      uses: actions/checkout@v3
    - name: Restore base environment
      id: restore-clones
      uses: actions/cache@v3
      with:
        path: clones
        key: >-
          ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-${{ hashFiles('scripts/setup.sh') }}-${{ hashFiles('scripts.diffy.sh') }}
    - name: Cache base diff environment
      id: cache-clones
      if: steps.restore-clones.outputs.cache-hit != 'true'
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          clones
          **/node_modules
        key: >-
          ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-${{ hashFiles('scripts/setup.sh') }}-${{ hashFiles('scripts.diffy.sh') }}
        restore-keys: |
          ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-${{ hashFiles('scripts/setup.sh') }}-${{ hashFiles('scripts.diffy.sh') }}
          ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-${{ hashFiles('scripts/setup.sh') }}
          ${{ env.CACHE_VERSION}}-${{ runner.os }}-base
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install diff2html
      run: npm -g install diff2html-cli diff2html


  prepare-smile:
    runs-on: ubuntu-latest
    name: Smile Prepare environment
    needs: prepare
    steps:

    - name: Checkout HA core
      uses: actions/checkout@v3
      with:
        repository: home-assistant/core
        path: clones/beta/ha-core
    - name: Checkout Plugwise fork of HA core
      uses: actions/checkout@v3
      with:
        repository: plugwise/home-assistant.core
        ssh-key: ${{ secrets.hacore_deploykey }}
        path: clones/beta/pw-core
        fetch-depth: 0
    - name: Checkout beta component (branch-switch)
      uses: actions/checkout@v3
      with:
        repository: plugwise/plugwise-beta
        ssh-key: ${{ secrets.plugwise_deploykey }}
        path: clones/beta
        fetch-depth: 0

  prepare-usb:
    runs-on: ubuntu-latest
    name: USB Prepare environment
    needs: prepare
    steps:

    - name: Checkout HA core for usb-beta
      uses: actions/checkout@v3
      with:
        repository: home-assistant/core
        path: clones/usb-beta/ha-core
    - name: Checkout Plugwise fork of HA core for usb-beta
      uses: actions/checkout@v3
      with:
        repository: plugwise/home-assistant.core
        ssh-key: ${{ secrets.hacore_deploykey }}
        path: clones/usb-beta/pw-core
        fetch-depth: 0
    - name: Checkout usb-beta component (branch-switch)
      uses: actions/checkout@v3
      with:
        repository: plugwise/plugwise-beta
        ssh-key: ${{ secrets.plugwise_deploykey }}
        path: clones/usb-beta
        fetch-depth: 0

  checkout-smile:
    runs-on: ubuntu-latest
    name: Smile Prepare environment
    needs: prepare-smile
    steps:

    - name: Checkout beta component (main-branch)
      uses: actions/checkout@v3
      with:
        repository: plugwise/plugwise-beta
        ref: main
        ssh-key: ${{ secrets.plugwise_deploykey }}
        path: clones/beta-main

  checkout-usb:
    runs-on: ubuntu-latest
    name: USB Prepare environment
    needs: prepare-usb
    steps:

    - name: Checkout usb-beta component (main-branch)
      uses: actions/checkout@v3
      with:
        repository: plugwise/plugwise_usb-beta
        ref: main
        ssh-key: ${{ secrets.plugwise_deploykey }}
        path: clones/usb-beta-main


  diffy-smile:
    runs-on: ubuntu-latest
    name: Smile run diff
    needs: checkout-usb
    steps:

    - name: Setup SSH Keys and known_hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.PROGRESS_DEPLOYKEY }}"
    - name: Setup clone (beta)
      run: scripts/setup.sh beta
    - name: Run diff (beta)
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: scripts/diffy.sh beta

  diffy-usb:
    runs-on: ubuntu-latest
    name: USB run diff
    needs: checkout-usb
    steps:

    - name: debug
      run: pwd
    - name: Setup SSH Keys and known_hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.PROGRESS_DEPLOYKEY }}"
    - name: Setup clone (usb-beta)
      run: scripts/setup.sh usb-beta
    - name: Run diff (usb-beta)
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: scripts/diffy.sh usb-beta




